services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - './src:/var/www/html'
      - './games:/var/www/games'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
    depends_on:
      - php
      - mysql
    networks:
      - app-network

  php:
    build:
      dockerfile: docker/dokerfiles/php.Dockerfile
    environment:
      - PHP_IDE_CONFIG=serverName=laravel_docker
    volumes:
      - './src:/var/www/html'
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "meddb"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "rootpassword"
    volumes:
      - 'mysql_data:/var/lib/mysql'
      - './docker/mysql/init:/docker-entrypoint-initdb.d'
    ports:
      - "3306:3306"
    networks:
      - app-network

  composer:
    build:
      dockerfile: docker/dokerfiles/composer.Dockerfile
    volumes:
      - './src:/var/www/html'
    command: composer install --ignore-platform-reqs
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge