services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
    depends_on:
      - postgres
      - php

  php:
    build:
      dockerfile: docker/dokerfiles/php.Dockerfile
    environment:
      - PHP_IDE_CONFIG=serverName=laravel_docker
    volumes:
      - './src:/var/www/html'
      - './docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini'

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: "meddb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'  # Основное хранилище данных
      - './docker/postgres/init:/docker-entrypoint-initdb.d'  # Скрипты инициализации
    ports:
      - "5433:5433"

  composer:
    build:
      dockerfile: docker/dokerfiles/composer.Dockerfile
    volumes:
      - './src:/var/www/html'

  artisan:
    build:
      dockerfile: docker/dokerfiles/php.Dockerfile
    volumes:
      - './src:/var/www/html'
    entrypoint: [ "php", "/var/www/html/artisan" ]

volumes:
  postgres_data: